spring:
  application:
    name: spring-app
  datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: pass@123
      driver-class-name: org.postgresql.Driver
#      database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
